Web App via ASP.NET/MetzNenger.BackOffice.Web.UI/Controllers/ChannelsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MetzNenger.Core.Data.Models;

namespace MetzNenger.BackOffice.Web.UI.Controllers
{
    public class ChannelsController : Controller
    {
        private readonly MetzengerContext _context;

        public ChannelsController(MetzengerContext context)
        {
            _context = context;
        }

        // GET: Channels
        public async Task<IActionResult> Index()
        {
              return _context.Channels != null ? 
                          View(await _context.Channels.ToListAsync()) :
                          Problem("Entity set 'MetzengerContext.Channels'  is null.");
        }

        // GET: Channels/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Channels == null)
            {
                return NotFound();
            }

            var channel = await _context.Channels
                .FirstOrDefaultAsync(m => m.ChannelId == id);
            if (channel == null)
            {
                return NotFound();
            }

            return View(channel);
        }

        // GET: Channels/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Channels/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ChannelId,ChannelName")] Channel channel)
        {
            if (ModelState.IsValid)
            {
                _context.Add(channel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(channel);
        }

        // GET: Channels/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Channels == null)
            {
                return NotFound();
            }

            var channel = await _context.Channels.FindAsync(id);
            if (channel == null)
            {
                return NotFound();
            }
            return View(channel);
        }

        // POST: Channels/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ChannelId,ChannelName")] Channel channel)
        {
            if (id != channel.ChannelId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(channel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ChannelExists(channel.ChannelId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(channel);
        }

        // GET: Channels/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Channels == null)
            {
                return NotFound();
            }

            var channel = await _context.Channels
                .FirstOrDefaultAsync(m => m.ChannelId == id);
            if (channel == null)
            {
                return NotFound();
            }

            return View(channel);
        }

        // POST: Channels/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Channels == null)
            {
                return Problem("Entity set 'MetzengerContext.Channels'  is null.");
            }
            var channel = await _context.Channels.FindAsync(id);
            if (channel != null)
            {
                _context.Channels.Remove(channel);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ChannelExists(int id)
        {
          return (_context.Channels?.Any(e => e.ChannelId == id)).GetValueOrDefault();
        }
    }
}

Web App via ASP.NET/MetzNenger.BackOffice.Web.UI/Controllers/LoginController.cs
using MetzNenger.Core.Data.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace MetzNenger.BackOffice.Web.UI.Controllers
{
    public class LoginController : Controller
    {
        #region Proprieté
        private MetzengerContext _Context { get; set; }
        #endregion
        public LoginController(MetzengerContext _context)
        {
            _Context = _context;
        }

        
        
    }
}

Web App via ASP.NET/MetzNenger.BackOffice.Web.UI/Controllers/UserAccountsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MetzNenger.Core.Data.Models;

namespace MetzNenger.BackOffice.Web.UI.Controllers
{
    public class UserAccountsController : Controller
    {
        private readonly MetzengerContext _context;

        public UserAccountsController(MetzengerContext context)
        {
            _context = context;
        }

        // GET: UserAccounts
        public async Task<IActionResult> Index()
        {
            var metzengerContext = _context.UserAccounts.Include(u => u.Class);
            return View(await metzengerContext.ToListAsync());
        }

        // GET: UserAccounts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.UserAccounts == null)
            {
                return NotFound();
            }

            var userAccount = await _context.UserAccounts
                .Include(u => u.Class)
                .FirstOrDefaultAsync(m => m.AccountId == id);
            if (userAccount == null)
            {
                return NotFound();
            }

            return View(userAccount);
        }

        // GET: UserAccounts/Create
        public IActionResult Create()
        {
            ViewData["ClassId"] = new SelectList(_context.Classrooms, "ClassId", "ClassName");
            return View();
        }

        // POST: UserAccounts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("AccountId,Email,Password,Nickname,AdministrativeStatus,LastName,FirstName,Phone,IsValidated,IsAdmin,ClassId")] UserAccount userAccount)
        {
            if (ModelState.IsValid)
            {
                _context.Add(userAccount);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ClassId"] = new SelectList(_context.Classrooms, "ClassId", "ClassName", userAccount.ClassId);
            return View(userAccount);
        }

        // GET: UserAccounts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.UserAccounts == null)
            {
                return NotFound();
            }

            var userAccount = await _context.UserAccounts.FindAsync(id);
            if (userAccount == null)
            {
                return NotFound();
            }
            ViewData["ClassId"] = new SelectList(_context.Classrooms, "ClassId", "ClassName", userAccount.ClassId);
            return View(userAccount);
        }

        // POST: UserAccounts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("AccountId,Email,Password,Nickname,AdministrativeStatus,LastName,FirstName,Phone,IsValidated,IsAdmin,ClassId")] UserAccount userAccount)
        {
            if (id != userAccount.AccountId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(userAccount);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UserAccountExists(userAccount.AccountId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ClassId"] = new SelectList(_context.Classrooms, "ClassId", "ClassName", userAccount.ClassId);
            return View(userAccount);
        }

        // GET: UserAccounts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.UserAccounts == null)
            {
                return NotFound();
            }

            var userAccount = await _context.UserAccounts
                .Include(u => u.Class)
                .FirstOrDefaultAsync(m => m.AccountId == id);
            if (userAccount == null)
            {
                return NotFound();
            }

            return View(userAccount);
        }

        // POST: UserAccounts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.UserAccounts == null)
            {
                return Problem("Entity set 'MetzengerContext.UserAccounts'  is null.");
            }
            var userAccount = await _context.UserAccounts.FindAsync(id);
            if (userAccount != null)
            {
                _context.UserAccounts.Remove(userAccount);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UserAccountExists(int id)
        {
          return (_context.UserAccounts?.Any(e => e.AccountId == id)).GetValueOrDefault();
        }
    }
}

Web App via ASP.NET/MetzNenger.BackOffice.Web.UI/Controllers/UtilisateurController.cs
using MetzNenger.Core.Data.Models;
using Microsoft.AspNetCore.Mvc;
using Otherscript;

namespace MetzNenger.BackOffice.Web.UI.Controllers
{
    public class UtilisateurController : Controller
    {
        #region Champs privés
        private MetzengerContext _context ;
        #endregion
        #region Contruscteur
        public UtilisateurController(MetzengerContext _context)
        {
            this._context = _context;
        }
        #endregion
        #region Méthode publique
        /// <summary>
        /// methode qui permet de crée une page web ....
        /// </summary>
        /// <returns></returns>
        public ActionResult Create()
        {
            return this.View();
        }
        [HttpPost]
        public ActionResult Create(UserAccount utilisateur)
        {
            this._context.UserAccounts.Add(utilisateur);
            this._context.SaveChanges();
            return this.View();
        }
        /// <summary>
        /// on crée un utilisateur null puis on lui met un useracount qui est egal à l'id  qu'on passe en paramettre
        /// de la methode.
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult Edit(int id)
        {
            UserAccount utilisateur = null;
            utilisateur = this._context.UserAccounts.First(item => item.AccountId == id);
            return this.View(utilisateur);
        }
        [HttpPost]
        public ActionResult Edit(UserAccount utilisateur)
        {
            // 1er facon de modifier: modifie tout
            //this._context.UserAccounts.Update(utilisateur);
            //2eme methode : attach permet de "suivre un objet" puis apres on utilise entry afin de recupere les donné de la classe suivie et on 
            //check si il y a eu des modification en sommes la 2eme methode permet de bien gerer les champ qu'on peut modifier ou non ....
            this._context.Attach<UserAccount>(utilisateur);
            this._context.Entry(utilisateur).Property(item => item.Nickname).IsModified = true;
            this._context.SaveChanges();
            return this.View(utilisateur);
        }
        public ActionResult Login()
        {

            return this.View();
        }
        [HttpPost]
        public ActionResult Check(IFormCollection form)
        {
            string email = ToolBox.HashString(form["emailInput"]);
            string password = ToolBox.HashString(form["passwordInput"]);
            
            if (this._context.UserAccounts.Where(u=>u.Email==email && u.Password==password && u.IsValidated).Any())
            {
                UserAccount user = this._context.UserAccounts.Where(u => u.Email == email && u.Password == password && u.IsValidated).First();
                this.ViewBag.UserListToValidate=this._context.UserAccounts.Where(u =>u.IsValidated==false).ToList();
                this.ViewBag.Channels = this._context.Channels.ToList();
                return this.View(user);
            }
            else
            {
                //pour renvoyer vers une methode "actionResult"
                return RedirectToAction(nameof(Login)) ;
            }
            

            
        }
        #endregion
    }
}

Web App via ASP.NET/MetzNenger.BackOffice.Web.UI/Views/Utilisateur/Check.cshtml
@using MetzNenger.Core.Data.Models
@model MetzNenger.Core.Data.Models.UserAccount

@{
    ViewData["Title"] = "MonCompte";
    List<UserAccount> listuser = this.ViewBag.UserListToValidate;
    var listItems = listuser.Select(item => new SelectListItem() {Text=item.Nickname,Value= item.AccountId.ToString() }).ToList();
}

<h1>Bienvenue @Html.DisplayFor(model => model.Nickname)</h1>
<div class="form-group">
@*    <div class="col-sm-4">
        Utilisateur à valider :
    <select asp-for="AccountId" asp-items="listItems"></select>
    <input type="submit" value="Valider" class="btn colorsMnsOrange m-2" />
    </div>*@
    <a type="submit"  class="btn colorsMnsOrange m-2" asp-controller="UserAccounts" asp-action="Index" >Utilisateur</a>
</div>
<div class="form-group">

        <a type="submit"  class="btn colorsMnsOrange m-2" asp-controller="Channels" asp-action="Index" >Channels</a>
    </div>
    </div>
</div>
<div class="form-group">
    
</div>
@*<div>
    <h4>Mon Compte</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nickname)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nickname)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AdministrativeStatus)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AdministrativeStatus)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Phone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Phone)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Class)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Class.ClassName)
        </dd>
    </dl>
</div>*@
<div>
    <a asp-action="Edit" asp-route-id="@Model?.AccountId">Edit</a> |
    <a asp-action="Index">Log Out</a>
</div>

Web App via ASP.NET/MetzNenger.BackOffice.Web.UI/Views/Utilisateur/Create.cshtml
@model MetzNenger.Core.Data.Models.UserAccount

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>UserAccount</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nickname" class="control-label"></label>
                <input asp-for="Nickname" class="form-control" />
                <span asp-validation-for="Nickname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AdministrativeStatus" class="control-label"></label>
                <input asp-for="AdministrativeStatus" class="form-control" />
                <span asp-validation-for="AdministrativeStatus" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Phone" class="control-label"></label>
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
            @*<div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsValidated" /> @Html.DisplayNameFor(model => model.IsValidated)
                </label>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsAdmin" /> @Html.DisplayNameFor(model => model.IsAdmin)
                </label>
            </div>*@
            @*<div class="form-group">
                <label asp-for="ClassId" class="control-label"></label>
                <select asp-for="ClassId" class ="form-control" asp-items="ViewBag.ClassId"></select>
            </div>*@
            <div class="form-group">
                <input type="submit" value="Create" class="btn colorsMnsOrange" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Web App via ASP.NET/MetzNenger.BackOffice.Web.UI/Views/Utilisateur/Edit.cshtml
@model MetzNenger.Core.Data.Models.UserAccount

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>UserAccount</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @*<input type="hidden" asp-for="AccountId" />*@
            <div class="form-group">
                <label asp-for="Nickname" class="control-label"></label>
                <input asp-for="Nickname" class="form-control" />
                <span asp-validation-for="Nickname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label  asp-for="AdministrativeStatus" class="control-label"></label>
                <input asp-for="AdministrativeStatus" class="form-control" />
                <span asp-validation-for="AdministrativeStatus" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Phone" class="control-label"></label>
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
            @*<div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsValidated" /> @Html.DisplayNameFor(model => model.IsValidated)
                </label>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsAdmin" /> @Html.DisplayNameFor(model => model.IsAdmin)
                </label>
            </div>*@
            <div class="form-group">
                <label asp-for="ClassId" class="control-label"></label>
                <select asp-for="ClassId" class="form-control" asp-items="ViewBag.ClassId"></select>
                <span asp-validation-for="ClassId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn colorsMnsOrange" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Web App via ASP.NET/MetzNenger.BackOffice.Web.UI/Views/Utilisateur/Login.cshtml
@model MetzNenger.Core.Data.Models.UserAccount

<div class="container ">
	@*<p>Utilisateur</p>
	<input type="email" id="user" />*@
@*	<p>Password</p>*@
	@*<input type="password" id="password" />*@
    <form id="profile-form" method="post" >
	<div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input name="emailInput" asp-for="Email" class="form-control" type="email" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
	<div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input name="passwordInput" asp-for="Password" class="form-control" type="password" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
			<div class="form-group">
                <input type="submit" value="Valider" class="btn colorsMnsOrange" asp-action="Check" />
            </div>
            </form>
	@*<div class="form-group m-2">
	<input type="submit" class="btn colorsMnsOrange" value"Edit">
	</div>*@
</div>