Web App via ASP.NET/MetzNenger.BackOffice.Web.UI/Controllers/UtilisateurController.cs
using MetzNenger.Core.Data.Models;
using Microsoft.AspNetCore.Mvc;
using Otherscript;

namespace MetzNenger.BackOffice.Web.UI.Controllers
{
    public class UtilisateurController : Controller
    {
        #region Champs privés
        private MetzengerContext _context ;
        #endregion
        #region Contruscteur
        public UtilisateurController(MetzengerContext _context)
        {
            this._context = _context;
        }
        #endregion
        #region Méthode publique
        /// <summary>
        /// methode qui permet de crée une page web ....
        /// </summary>
        /// <returns></returns>
        public ActionResult Create()
        {
            return this.View();
        }
        [HttpPost]
        public ActionResult Create(UserAccount utilisateur)
        {
            this._context.UserAccounts.Add(utilisateur);
            this._context.SaveChanges();
            return this.View();
        }
        /// <summary>
        /// on crée un utilisateur null puis on lui met un useracount qui est egal à l'id  qu'on passe en paramettre
        /// de la methode.
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult Edit(int id)
        {
            UserAccount utilisateur = null;
            utilisateur = this._context.UserAccounts.First(item => item.AccountId == id);
            return this.View(utilisateur);
        }
        [HttpPost]
        public ActionResult Edit(UserAccount utilisateur)
        {
            // 1er facon de modifier: modifie tout
            //this._context.UserAccounts.Update(utilisateur);
            //2eme methode : attach permet de "suivre un objet" puis apres on utilise entry afin de recupere les donné de la classe suivie et on 
            //check si il y a eu des modification en sommes la 2eme methode permet de bien gerer les champ qu'on peut modifier ou non ....
            this._context.Attach<UserAccount>(utilisateur);
            this._context.Entry(utilisateur).Property(item => item.Nickname).IsModified = true;
            this._context.SaveChanges();
            return this.View(utilisateur);
        }
        public ActionResult Login()
        {

            return this.View();
        }
        [HttpPost]
        public ActionResult Check(IFormCollection form)
        {
            string email = ToolBox.HashString(form["emailInput"]);
            string password = ToolBox.HashString(form["passwordInput"]);
            
            if (this._context.UserAccounts.Where(u=>u.Email==email && u.Password==password && u.IsValidated).Any())
            {
                UserAccount user = this._context.UserAccounts.Where(u => u.Email == email && u.Password == password && u.IsValidated).First();
                this.ViewBag.UserListToValidate=this._context.UserAccounts.Where(u =>u.IsValidated==false).ToList();
                this.ViewBag.Channels = this._context.Channels.ToList();
                return this.View(user);
            }
            else
            {
                //pour renvoyer vers une methode "actionResult"
                return RedirectToAction(nameof(Login)) ;
            }
            

            
        }
        #endregion
    }
}

Web App via ASP.NET/MetzNenger.BackOffice.Web.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MetzNenger.BackOffice.Web.UI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MetzNenger.BackOffice.Web.UI.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light  border-bottom box-shadow mb-3 colorMnsBleu">
            <div class="container-fluid">
                <a class="navbar-brand text-white" asp-area="" asp-controller="Home" asp-action="Index">
                    <img class="img-fluid" src="~/logo-mns-02.png" width="200"/>
                    </a>
                <button class="navbar-toggler colorsMnsOrange" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Utilisateur" asp-action="Login">LogIn</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white " asp-area="" asp-controller="Utilisateur" asp-action="Create">Register</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - MetzNenger.BackOffice.Web.UI - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>